[project]
name = "crew-ai-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[google-genai,tools]>=1.5.0",
    "notebook>=7.5.0",
]
